include $(PATHS_FILE)
include $(EXTERN_LIBS)
include $(COMPILER_OPTIONS_FILE)

# Flags _________________________________________________________________
ifeq ($(COMPILER), mpixlf95_r)
	LIBS =  $(IO_LIB) $(HDF5_LIB) $(SCHEMES_LIB) $(SOLVERS_LIB) $(MISCELLANEOUS_LIB) $(LIBS_FFT) $(DECOMP2D_LIB) $(LAPACK_LIB) 
endif

ifeq ($(COMPILER),ifort)
	LIBS =  $(SOLVERS_LIB) $(MISCELLANEOUS_LIB) $(LIBS_FFT) $(SCHEMES_LIB) $(LIBS_MKL) $(DECOMP2D_LIB)
endif

ifeq ($(COMPILER),gfortran)
	LIBS 		= $(IO_LIB) $(HDF5_LIB) $(SCHEMES_LIB) $(SOLVERS_LIB) $(MISCELLANEOUS_LIB) $(LIBS_FFT) $(DECOMP2D_LIB) $(LAPACK_LIB)
endif

FFLAGS		= -c $(COMPILER_OPTIONS) $(DECOMP2D_INC)
INCS 		= $(FLAG_FFT) $(HDF5_INC) $(IO_INC) $(SOLVERS_INC) $(MISCELLANEOUS_INC) $(SCHEMES_INC)


build 	: anim2D.o  boundaries.o DNS_settings.o IBM_data.o IBM_settings.o mesh_settings.o physical_fields.o schemes_interface.o \
			  workspace_view.o

%.o:	%.f90
	$(FF) $(FFLAGS) $(INCS) $<
	
clean:
	rm ./*.o; rm ./*.mod;