include $(PATHS_FILE)
include $(SYSTEM_INFO_FILE)
include $(COMPILER_OPTIONS_FILE)


FFLAGS= -c $(COMPILER_OPTIONS) $(MISCELLANEOUS_INC)
SOURCES=sources

DRP=$(SOURCES)/schemes3D/DRP
O2=$(SOURCES)/schemes3D/O2

build: ./lib/libschemes.a

./lib/libschemes.a: $(SOURCES)/collocated_schemes.f90 $(SOURCES)/staggered_schemes.f90
	$(FF) $(FFLAGS) $(SOLVERS_INC)  $(SOURCES)/schemes_settings.f90; 	\
	$(FF) $(FFLAGS) $(SOLVERS_INC)  $(SOURCES)/staggered_schemes.f90; 	\
	$(FF) $(FFLAGS) $(SOLVERS_INC)  $(SOURCES)/collocated_schemes.f90; 	\
	$(FF) $(FFLAGS) $(SOLVERS_INC)  $(DRP)/DRP_D0s.f90; 	\
	$(FF) $(FFLAGS) $(SOLVERS_INC)  $(DRP)/DRP_D1s.f90; 	\
	$(FF) $(FFLAGS) $(SOLVERS_INC)  $(DRP)/DRP_D1c.f90; 	\
	$(FF) $(FFLAGS) $(SOLVERS_INC)  $(DRP)/DRP_D2c.f90; 	\
	$(FF) $(FFLAGS) $(SOLVERS_INC)  $(O2)/O2_D0s.f90; 	\
	$(FF) $(FFLAGS) $(SOLVERS_INC)  $(O2)/O2_D1s.f90; 	\
	$(FF) $(FFLAGS) $(SOLVERS_INC)  $(O2)/O2_D1c.f90; 	\
	$(FF) $(FFLAGS) $(SOLVERS_INC)  $(O2)/O2_D2c.f90; 	\
	$(AR_CMD) -q ./lib/libschemes.a ./*.o; 	\
	mv ./*.mod ./include;							\
	rm ./*.o;

clean:
	rm ./lib/*; rm ./include/*


