include $(PATHS_FILE)
include $(EXTERN_LIBS)
include $(COMPILER_OPTIONS_FILE)

# Flags _________________________________________________________________
ifeq ($(COMPILER), mpixlf95_r)
	LIBS =  $(IO_LIB) $(HDF5_LIB) $(SCHEMES_LIB) $(SOLVERS_LIB) $(MISCELLANEOUS_LIB) $(LIBS_FFT) $(DECOMP2D_LIB) $(LAPACK_LIB) 
endif

ifeq ($(COMPILER),ifort)
	LIBS =  $(SOLVERS_LIB) $(MISCELLANEOUS_LIB) $(LIBS_FFT) $(SCHEMES_LIB) $(LIBS_MKL) $(DECOMP2D_LIB)
endif

ifeq ($(COMPILER),gfortran)
	LIBS 		= $(IO_LIB) $(HDF5_LIB) $(SCHEMES_LIB) $(SOLVERS_LIB) $(MISCELLANEOUS_LIB) $(LIBS_FFT) $(DECOMP2D_LIB) $(LAPACK_LIB)
endif

FFLAGS		= -c $(COMPILER_OPTIONS) $(DECOMP2D_INC)
LDFLAG		= $(COMPILER_OPTIONS) -o
DATAS		= ./datas
SCALAR		= ./passive_scalar

INCS 		= $(FLAG_FFT) $(HDF5_INC) $(IO_INC) $(SOLVERS_INC) $(MISCELLANEOUS_INC) $(SCHEMES_INC) -I ./datas 

OBJ		= $(DATAS)/anim2D.o $(DATAS)/boundaries.o $(DATAS)/mesh_settings.o $(DATAS)/DNS_settings.o $(DATAS)/schemes_interface.o $(DATAS)/physical_fields.o \
		  $(DATAS)/workspace_view.o $(DATAS)/IBM_settings.o $(DATAS)/IBM_data.o $(SCALAR)/scalar_datas.o $(SCALAR)/solver.o $(SCALAR)/initializer.o velocity_analyzer$(SCHEME).o \
		  Turbulene_generator.o mesh_generator.o BC_controller.o Poisson_solver.o Poisson_generic_solver.o IBM.o NS_solver$(SCHEME).o IO_handler.o schemes_loader.o open.o main.o


# Dependencies __________________________________________________________

#$(SCALAR)/scalar_datas.o 	: $(DATAS)/mesh_settings.o 
$(SCALAR)/initializer.o 	: $(SCALAR)/scalar_datas.o 
$(SCALAR)/solver.o 	: $(SCALAR)/scalar_datas.o IO_handler.o
open.o 				: 
schemes_loader.o 	: 
IO_handler.o 		: 
Turbulene_generator.o	: $(SCALAR)/scalar_datas.o 
velocity_analyzer$(SCHEME).o	: 
mesh_generator.o	: 
BC_controller.o 	: 
Poisson_solver.o	: 
IBM.o				: $(DATAS)/IBM_data.o $(DATAS)/workspace_view.o
NS_solver$(SCHEME).o 	: $(DATAS)/mesh_settings.o $(DATAS)/schemes_interface.o BC_controller.o $(DATAS)/boundaries.o $(DATAS)/DNS_settings.o \
			  $(DATAS)/physical_fields.o $(DATAS)/workspace_view.o IBM.o Poisson_solver.o Poisson_generic_solver.o velocity_analyzer$(SCHEME).o
main.o			: $(DATAS)/physical_fields.o $(DATAS)/mesh_settings.o $(DATAS)/DNS_settings.o $(DATAS)/IBM_settings.o $(DATAS)/IBM_data.o $(DATAS)/anim2D.o \
			  $(DATAS)/workspace_view.o $(SCALAR)/scalar_datas.o $(SCALAR)/initializer.o $(SCALAR)/solver.o schemes_loader.o IO_handler.o BC_controller.o Turbulene_generator.o \
			  mesh_generator.o open.o NS_solver$(SCHEME).o
IOtest.o		: $(DATAS)/physical_fields.o $(DATAS)/mesh_settings.o $(DATAS)/DNS_settings.o $(DATAS)/workspace_view.o \
			  schemes_loader.o IO_handler.o BC_controller.o Turbulene_generator.o mesh_generator.o NS_solver.o

# Rules _________________________________________________________________
build:	main.o    
	$(FF) $(LDFLAG) $(EXEC_NAME) $(OBJ) $(LIBS)
	
	
clean:
	rm ./$(EXEC_NAME);			\
	rm ./*.o; rm ./*.mod; 			\
	rm $(DATAS)/*.o; rm $(DATAS)/*.mod;	\
	rm $(SCALAR)/*.o; rm $(SCALAR)/*.mod;

	
$(DATAS)/%.o:	$(DATAS)/%.f90
	make -C $(DATAS) PATHS_FILE=$(PATHS_FILE) ;

	
$(SCALAR)/%.o:	$(SCALAR)/%.f90
	$(FF) -o $@ $(FFLAGS) $(INCS)  $<
	
%.o:	%.f90
	$(FF) $(FFLAGS) $(INCS) $<